### PR TITLE
Workspace swipe rework

### LINKED ISSUE #113: Workspace swipe rework
Some time ago Hyprland added touch gestures for workspace swipe, so now we can use the slightly less hacky internal APIs for our own.

- The new workspace swipe should be implemented using: `g_pInputManager->beginWorkspaceSwipe`, `updateWorkspaceSwipe` and `endWorkspaceSwipe`. These are private methods so the following hack needs to be used:

```cpp
#define private public
#include <hyprland/src/...>
#undef private
```

(even the official hyprexpo plugin does this so don't think about it)

- Take a look at how the gestures are handled in https://github.com/hyprwm/Hyprland/blob/main/src/managers/input/Touch.cpp

- in hyprgrass, emulateSwipeBegin would be a good place to start

### LINKED ISSUE #114: config: Move to hyprlang keywords
Hyprlang allows us to use syntax like this:

```
plugins = {
  touch_gestures = {
    bind = , swipe:3:d, exec, thing
    bind = ...
  }
}
```

- Existing support for Hyprland's bind keyword can be left as-is

- binds introduced by the new keyword should be added to `GestureManager.internalBinds`

- the gesture handlers already make use of `internalBinds`, but noone has ever tested this functionality so I wouldn't be surprised if it doesn't work

### PR DESCRIPTION
**Pull request by horriblename**
fixes #113, #105

### CODE REVIEW

**Comment by horriblename** [comment]
@system64fumo test would be appreciated

**Comment by System64fumo** [comment]
Bet

**Comment by System64fumo** [comment]
I'm afraid that it's still broken and results in a crash when the gesture is done,
Unsure if this is due to me using a custom version of Hyprland on my phone (Patched version with forced touchscreen capabilities)
But i will check on my tablet and get back to you

**Comment by System64fumo** [comment]
Confirmed, same behavior on tablet too

**Comment by horriblename** [comment]
ugh send crash logs? I think they're in .cache/hyprland

**Comment by System64fumo** [comment]
As a sanity check i just updated to the latest-git version
It no longer crashes
But it's still inverted

**Comment by horriblename** [comment]
ok that's just me being dumb, very fixable

**Comment by horriblename** [comment]
done

**Comment by System64fumo** [comment]
I don't know?
Still inverted for me?

**Comment by horriblename** [comment]
doubt this would help but, give it a go

**Comment by System64fumo** [comment]
Nope, still inverted

**Comment by System64fumo** [comment]
Still broken i'm afraid.
Since you don't have a touchscreen maybe [this](https://www.waveshare.com/product/7inch-hdmi-lcd-h.htm) will help you debug this?
Just try to find a knockoff on ebay or aliexpress for cheaper or something.

**Comment by horriblename** [comment]
I actually just installed linux yesterday.

still figuring out how to fix this thing, but I can test things now, thx for your help

**Comment by System64fumo** [comment]
Happy to help,
Keep me updated on the matter.

**Comment by horriblename** [comment]
I am constantly impressed by my own stupidity

Anyway, direction should be fixed now, though now I need to figure out why the gestures are not one-to-one anymore

plus edge workspace swipe crashes on lifting the finger. Gonna update hl tomorrow and hope it fixes itself

**Pull request merged**
