### PR TITLE
HyprlandAPI Breaking Change Fix

### PR DESCRIPTION
**Pull request by nine7nine**
Callbacks need more adjustments as of: https://github.com/hyprwm/Hyprland/commit/e91513a5e8953cfbb69320d94e495ccf2d4d58f3

 Tested on my end: Hyprgrass Plugin loads and works as expected with this change.

### CODE REVIEW

**Comment by nine7nine** [comment]
Hey @horriblename. More breakage in HyprlandAPI for plugins.

 You can check the 'official' hyprland-plugins they've made similar adjustments, as did KZDKM/Hyprspace, which I used as references to fix your plugin. eg: https://github.com/KZDKM/Hyprspace/commit/983cb8d324e7495e0514820768cbdcecebc5bd2b
 
 I think your nix build test fails -- as you probably need to update nix stuff against current hyprland/main ... unfortunately, I can't test that: I don't use nix

**Comment by horriblename** [comment]
LGTM will update nix later, thanks!

**Review by horriblename — APPROVED** [review]
LGTM thanks

**Comment by nine7nine** [comment]
Not a problem at all. Glad to help out!

btw, that hpyrpm: pin_commits[] commit will allow versioning / building against different releases/commits of Hyprland -- so that should ensure no one, regardless of hyprland version, will have any trouble using hyprpm to build hyprgrass.

I only just found out about that: so that is why I added the commit in.

**Pull request merged**
