### PR TITLE
Feat hl version check

### PR DESCRIPTION
**Pull request by horriblename**
Checks for version mismatch and sends a warning notification.

TODO:
- maybe skip check for `hyprland < 0.31`?

### CODE REVIEW

**Comment by horriblename** [comment]
@N0tallion6 @xVermillionx @crimist test pls

Hyprland must be latest (`43b39e0b` onwards) (I don't think AUR packages are working rn - either build from source or wait till its fixed)

let me know whether or not you get an error notification - if so send logs. If you don't get the error, let me know if gestures work

for hyprload this should should help:
```toml
plugins = [
      { git = "https://github.com/horriblename/hyprgrass", branch = "feat-hl-version-check" },
]
```

**Comment by crimist** [comment]
> 43b39e0b onwards

Given the way it currently checks version Hyprland has to built at exactly 5b8cfdf to not trigger the error.

ie building from current  `main` results in:

```
[ERR] [hyprgrass] version mismatch!
[ERR] [hyprgrass] | hyprgrass was built against: 5b8cfdf2efc44106b61e60c642fd964823fd89f3
[ERR] [hyprgrass] | actual hyprland version: 20e7ccd48033dcacc233b2a2f46d385049bf299b
[LOG]  [PluginSystem] Plugin hyprgrass loaded. Handle: 558b77b96dd0, path: "/home/crimist/git/hyprgrass/build/src/libhyprgrass.so", author: "horriblename", description: "Touchscreen gestures", version: "0.3"
```

> let me know if gestures work

After building Hyprland at exactly 5b8cfdf gestures do work for a couple swipes! And then promptly crash Hyprland...
I've attached a crash report though it's on the release build. Need to try sleep now but will post debug build crash logs later.

[hyprlandCrashReport301275.txt](https://github.com/horriblename/hyprgrass/files/12928510/hyprlandCrashReport301275.txt)

**Comment by crimist** [comment]
Looks like my symptoms perfectly match #47

**Comment by N0tallion6** [comment]
Sorry, just seen this @horriblename . I'll try to give this a test as soon as I can

**Comment by horriblename** [comment]
@crimist just like the logs said, your currently running hyprland is different from what hyprgrass was built with (in this case the running session is newer than the hyprgrass one). in short it's not my fault :D

the cause for the version mismatch is very dependent on your system and there's not much I can help with, the most probable cause I can think of:
- you installed hyprland from multiple sources (i.e. one compiled manually, another from pacman)
   - remove one of them - if you uninstall the manually compiled version you need to also `rm -rf /usr/local/include/ /usr/local/share/pkgconfig/hyprland.pc` cuz headers don't get deleted properly right now

**Comment by crimist** [comment]
@horriblename I misunderstood your comment about requiring "`43b39e0b` onwards" - seems like you were referencing the minimum version required to test this PR. I can confirm the new code works so you can merge this PR.

Regarding your latest comment - this crashing occurs on the `5b8cfdf` (0.31.0) build of Hyprland which does _not_ have a version mismatch with hyprgrass. I completely purged Hyprland including `/usr/local/include/* /usr/local/share/pkgconfig/hyprland.pc` before compiling and install from said commit so there shouldn't be any issues there. Will provide debug logs in #47

**Pull request merged**
